// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_s4xTA_m-Ad_OQCQqqFstLvmS7_AjR8c',
    appId: '1:318853381366:android:a6009e6ee267c73a6900d7',
    messagingSenderId: '318853381366',
    projectId: 'futsal-app-f3f37',
    storageBucket: 'futsal-app-f3f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVMyAJ5j3_M5b7Rl-1iBYwkhTMYuD56U',
    appId: '1:318853381366:ios:350b96cd3126f1c46900d7',
    messagingSenderId: '318853381366',
    projectId: 'futsal-app-f3f37',
    storageBucket: 'futsal-app-f3f37.firebasestorage.app',
    androidClientId: '318853381366-pahaa91nkm82nhbnh671v382ik2e1ctd.apps.googleusercontent.com',
    iosClientId: '318853381366-7u14u68aivjcjdfg1v79k0mvkv6im9at.apps.googleusercontent.com',
    iosBundleId: 'com.example.futsalApp',
  );

}